#!/bin/bash
getOs(){
    echo $(g++ --std=c++11 -MM $(find .|grep .cpp$) | grep -E "^[^:]*:"|sed 's/\(^[^:]*\):.*/\1/g')
}
if [[ $# > 3 ]] || [[ $# < 1 ]];then
    echo "Usage: $0 [Name] <CXXFLAGS> <LDFLAGS>";
    exit 1;
fi;
mkdir bin
echo "CXXFLAGS=--std=c++11 $2" > Makefile
echo "LDFLAGS=$3" >> Makefile
echo "oDir=obj/" >> Makefile
echo "oFiles=$(getOs)" >> Makefile
echo 'all: $(oDir)' >> Makefile
printf "\tmake --no-print-directory unclear\n" >>Makefile
printf "\tmake --no-print-directory comp\n">>Makefile
printf "\tmake --no-print-directory clear\n">>Makefile
echo '$(oDir):'>>Makefile
printf "\tmkdir "'$(oDir)'"\n">>Makefile
echo 'comp: $(oFiles)' >> Makefile
printf "\tg++ --std=c++11 -o bin/$1 "'$(oFiles) $(LDFLAGS)'"\n" >> Makefile
g++ --std=c++11 -MM $(find .|grep .cpp$ ) >> Makefile
echo "unclear:">> Makefile
printf "\t"'@if ! mv $(oDir)*.o .; then printf "";fi'"\n">> Makefile
echo "clear:">> Makefile
printf "\t"'@if ! mv *.o $(oDir); then printf "";fi'"\n">> Makefile
echo "clean:">> Makefile
printf "\t"'rm *.o ;rm $(oDir)*.o'"\n">> Makefile
exit 0;
