#!/bin/bash
#passwordGen: Script to ...
#Created: Wed Jun  8 12:16:13 CDT 2016
vowels=(a e i o u 4 0 1 y);
cons=(b c d f g h j k l m n p qu "r" s t v w x z st cr kr vr dr lt th);
randElement(){
    arr=($(eval 'echo ${'$1'[@]}'))
    echo ${arr[$(($RANDOM % ${#arr[@]}))]};
}
passwd=$(randElement "cons")
for((i=0;i<5;i++)); do
    passwd=$passwd$(randElement "vowels")$(randElement "cons")
done
echo $passwd
exit 0
